
name: Deploy to Azure

on:
  push:
    branches:
      - dist

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'movie-folders'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a6ddd571a92a42ad8bfc5f1df1c15f6f }}
        package: .